### ISSUE TITLE
Running melonbar immediately crashes

### ISSUE THREAD

**Issue by zeroeightysix** [onodera-punpun/melonbar#1]
OS: arch
i3 for wm.
go version: 1.11.4

installed using `go get github.com/onodera-punpun/melonbar`
running `/home/<user>/go/bin/melonbar` very briefly creates the bar window (for only a few milliseconds), exits right after with the following message: `2019/01/13 23:36:26 no such file or directory` (timestamp is just the current date)

**Comment by CamilleScholtz** [comment]
Many things are still hard-coded (because I want the user to edit the code to fit his or her needs). This is probably caused by https://github.com/onodera-punpun/melonbar/blob/master/blocks.go#L181

This line looks for a "todo" file, for me this file is `$HOME/.todo`. Either create this file or alter line.

I know this is not the perfect solutuon, maybe I'll create a `config.go` file where such valuas are set.

**Comment by zeroeightysix** [comment]
Yup, that solved it! Maybe try checking whether or not the file exists first and provide a more verbose error message for now (or put it in the readme)? Nice work on the bar so far.
